import MainLayout from "@/components/layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    category: "Getting Started",
    questions: [
      {
        question: "How do I create an account?",
        answer:
          "To create an account, click on the 'Sign Up' button in the top right corner of the homepage. You'll need to provide your email address and create a password. After signing up, you'll be prompted to complete our skin assessment quiz to help us create your personalized skincare routine.",
      },
      {
        question: "Is the skin assessment quiz mandatory?",
        answer:
          "Yes, the skin assessment quiz is a crucial part of our personalization process. It helps our AI understand your skin type, concerns, and goals to create a tailored skincare routine. The quiz takes about 5 minutes to complete, and you can always retake it if your skin concerns change.",
      },
      {
        question: "Can I use GlowSage on my mobile device?",
        answer:
          "Yes, GlowSage is fully responsive and works on all devices including smartphones, tablets, and desktop computers. We also have native mobile apps for iOS and Android that offer additional features like push notifications for routine reminders.",
      },
    ],
  },
  {
    category: "Skincare Routines",
    questions: [
      {
        question: "How are my skincare recommendations generated?",
        answer:
          "Your skincare recommendations are generated by our proprietary AI algorithm that analyzes your skin assessment responses, considering factors like your skin type, concerns, allergies, and budget. The algorithm then matches you with products and routines that have been effective for users with similar skin profiles.",
      },
      {
        question: "How often should I update my skincare routine?",
        answer:
          "We recommend reassessing your skincare needs every 3-6 months, or whenever you experience significant changes in your skin condition, environment, or lifestyle. You can retake the skin assessment quiz at any time to update your routine.",
      },
      {
        question: "Can I customize my recommended routine?",
        answer:
          "Yes, you can customize your recommended routine by adding, removing, or replacing products. However, we recommend following the recommended routine for at least 4-6 weeks to see results, as skincare products typically take time to show their full effects.",
      },
    ],
  },
  {
    category: "Progress Tracking",
    questions: [
      {
        question: "How do I track my skincare progress?",
        answer:
          "You can track your skincare progress through the 'Progress Photos' and 'Skin Metrics' tabs on your dashboard. We recommend taking photos in consistent lighting conditions every 2-4 weeks and updating your skin metrics regularly to monitor changes over time.",
      },
      {
        question: "Are my progress photos secure?",
        answer:
          "Yes, all your progress photos are encrypted and stored securely. Only you can access your photos, and we never share them with third parties without your explicit consent. You can delete your photos at any time from your account.",
      },
      {
        question: "What are skin metrics and how do they help?",
        answer:
          "Skin metrics are quantitative measurements of various aspects of your skin health, such as hydration level, oiliness, redness, texture, and overall condition. By tracking these metrics over time, you can objectively assess the effectiveness of your skincare routine and identify trends or patterns.",
      },
    ],
  },
  {
    category: "Account & Billing",
    questions: [
      {
        question: "How do I upgrade or downgrade my subscription?",
        answer:
          "You can change your subscription plan at any time by going to 'Profile' > 'Subscription' in your dashboard. If you upgrade, the change will take effect immediately. If you downgrade, the change will take effect at the end of your current billing cycle.",
      },
      {
        question: "What payment methods do you accept?",
        answer:
          "We accept all major credit cards (Visa, Mastercard, American Express, Discover), PayPal, and Apple Pay. All payments are processed securely through our payment processor, Stripe.",
      },
      {
        question: "How do I cancel my subscription?",
        answer:
          "You can cancel your subscription at any time by going to 'Profile' > 'Subscription' > 'Cancel Subscription'. Your account will remain active until the end of your current billing period. After cancellation, your account will revert to the Free plan, but you'll still have access to your data and progress history.",
      },
    ],
  },
  {
    category: "Technical Support",
    questions: [
      {
        question: "I forgot my password. How do I reset it?",
        answer:
          "To reset your password, click on 'Login' and then 'Forgot Password'. Enter the email address associated with your account, and we'll send you a password reset link. If you don't receive the email, please check your spam folder or contact our support team.",
      },
      {
        question: "The app is not working properly. What should I do?",
        answer:
          "If you're experiencing technical issues, try refreshing the page or clearing your browser cache. If the problem persists, please contact our support team at support@glowsage.com with details about the issue, including your device, browser, and steps to reproduce the problem.",
      },
      {
        question: "How do I delete my account?",
        answer:
          "To delete your account, go to 'Profile' > 'Settings' > 'Delete Account'. Please note that this action is irreversible and will permanently delete all your data, including progress photos, skin metrics, and routine history.",
      },
    ],
  },
];

export default function FAQPage() {
  return (
    <MainLayout>
      <div className="container max-w-4xl mx-auto py-20 px-4">
        <div className="space-y-4 mb-12 text-center">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Find answers to common questions about GlowSage and skincare
          </p>
        </div>

        <div className="space-y-8 mb-16">
          {faqs.map((category, index) => (
            <div key={index}>
              <h2 className="text-2xl font-bold mb-4">{category.category}</h2>
              <Accordion
                type="single"
                collapsible
                className="border rounded-lg"
              >
                {category.questions.map((faq, faqIndex) => (
                  <AccordionItem
                    key={faqIndex}
                    value={`item-${index}-${faqIndex}`}
                  >
                    <AccordionTrigger className="px-4 hover:no-underline">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4">
                      <p className="text-muted-foreground">{faq.answer}</p>
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          ))}
        </div>

        <div className="bg-muted/30 rounded-lg p-8 text-center">
          <h2 className="text-2xl font-bold mb-4">Still Have Questions?</h2>
          <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
            If you couldn't find the answer you were looking for, our support
            team is here to help.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Link to="/contact">
              <Button size="lg">Contact Support</Button>
            </Link>
            <Link to="/blog">
              <Button variant="outline" size="lg">
                Read Our Blog
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
